### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/root/flicker_2W_images/.ipynb_checkpoints'

### ISSUE THREAD

**Issue by blingsr** [liujiaheng/CompressionData#6]
0%|                                                                                                           | 0/1001 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "generatePatchFlickr.py", line 18, in process_image
    img = Image.open(seq_path)
  File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/root/flicker_2W_images/.ipynb_checkpoints'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "generatePatchFlickr.py", line 64, in <module>
    res = list(tqdm(p.imap(process_image, imgNames), total=len(imgNames)))
  File "/root/miniconda3/lib/python3.8/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/root/miniconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
IsADirectoryError: [Errno 21] Is a directory: '/root/flicker_2W_images/.ipynb_checkpoints'

**Comment by amelllllbrr** [comment]
i need th document of flicker_2W_images
